# Generated by Django 4.2.7 on 2023-11-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactname', models.CharField(max_length=30)),
                ('subject', models.CharField(max_length=500)),
            ],
        ),
    ]
