# Generated by Django 4.2.7 on 2023-11-19 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='contact@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.CharField(default='message', max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactname',
            field=models.CharField(default='name', max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(default='subject', max_length=100),
        ),
    ]
