# Generated by Django 4.2.7 on 2023-11-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0003_contact_email_contact_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='username',
            field=models.CharField(default='Username', max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='birthdate',
            field=models.DateField(default=1234),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='contact@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='fname', max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='gender',
            field=models.CharField(default='gender', max_length=15),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(default='lname', max_length=40),
        ),
        migrations.AlterField(
            model_name='member',
            name='password',
            field=models.CharField(default='xxx', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='phonenumber',
            field=models.IntegerField(default='1234567890'),
        ),
    ]
