# Generated by Django 4.2.7 on 2023-11-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0004_member_username_alter_member_birthdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='(about/')),
                ('name', models.CharField(max_length=50)),
                ('speciality', models.TextField()),
            ],
        ),
    ]
