# Generated by Django 4.2.7 on 2023-11-27 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0008_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classimage', models.ImageField(upload_to='(gallery/')),
                ('classname', models.CharField(max_length=50)),
                ('classdetails', models.TextField()),
            ],
        ),
    ]
