# Generated by Django 4.2.7 on 2023-11-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0009_classmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='email',
        ),
        migrations.AddField(
            model_name='subscription',
            name='subscribeemail',
            field=models.EmailField(default='mathewmaingi21@gmail.com', max_length=254, unique=True),
        ),
        migrations.AddField(
            model_name='trainer',
            name='specialitydescription',
            field=models.TextField(default='ext'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='trainer',
            name='image',
            field=models.ImageField(default='default.png', upload_to='my-trainers/'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(default='name', max_length=50),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='speciality',
            field=models.CharField(default='Mcube', max_length=500),
        ),
    ]
