# Generated by Django 4.2.7 on 2023-11-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0010_remove_subscription_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='fname', max_length=40)),
                ('lastname', models.CharField(default='lname', max_length=40)),
                ('password', models.CharField(default='xxx', max_length=10)),
                ('phonenumber', models.IntegerField(default='1234567890')),
                ('email', models.EmailField(default='contact@gmail.com', max_length=254)),
                ('birthdate', models.DateField(default=1234)),
                ('gender', models.CharField(default='gender', max_length=15)),
                ('username', models.CharField(default='Username', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainerpassword',
            field=models.CharField(default='12345', max_length=30),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='specialitydescription',
            field=models.TextField(default='Speciality'),
        ),
    ]
