# Generated by Django 4.2.7 on 2023-11-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GYM', '0014_recentpost_remove_blog_blogimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentpost',
            name='description',
            field=models.TextField(default='describe'),
        ),
    ]
